

package VISTA;

import MODELO.Class_01;


public class Form_01 extends javax.swing.JFrame {

   Class_01 oper=new Class_01 ();
    public Form_01() {
        initComponents();
        this.setBounds(100, 100, 500, 300);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Txt_num1 = new javax.swing.JTextField();
        Txt_num2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_rta = new javax.swing.JTextField();
        Btt_suma = new javax.swing.JButton();
        Btt_resta = new javax.swing.JButton();
        Btt_multi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Btt_exit = new javax.swing.JButton();
        Btt_new = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("INGRESO DE DATOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(63, 18, 302, 35);

        Txt_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_num1ActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_num1);
        Txt_num1.setBounds(170, 70, 89, 22);

        Txt_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_num2ActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_num2);
        Txt_num2.setBounds(170, 130, 89, 22);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setText("INGRESO NUMERO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 70, 170, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setText("INGRESO NUMERO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 160, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel4.setText("RESULTADO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 140, 21);

        Txt_rta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_rtaActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_rta);
        Txt_rta.setBounds(170, 170, 90, 22);

        Btt_suma.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Btt_suma.setText("+");
        Btt_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_sumaActionPerformed(evt);
            }
        });
        getContentPane().add(Btt_suma);
        Btt_suma.setBounds(300, 80, 50, 27);

        Btt_resta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Btt_resta.setText("-");
        getContentPane().add(Btt_resta);
        Btt_resta.setBounds(300, 120, 50, 27);

        Btt_multi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Btt_multi.setText("*");
        Btt_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_multiActionPerformed(evt);
            }
        });
        getContentPane().add(Btt_multi);
        Btt_multi.setBounds(300, 160, 50, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Btt_exit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Btt_exit.setText("EXIT");
        Btt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_exitActionPerformed(evt);
            }
        });

        Btt_new.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Btt_new.setText("NUEVO");
        Btt_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Btt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Btt_new, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btt_exit)
                    .addComponent(Btt_new))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 210, 300, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_num2ActionPerformed

    private void Btt_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_newActionPerformed
        // TODO add your handling code here:
        Txt_num1.setText("");
        Txt_num2.setText("");
        Txt_rta.setText("");
        Txt_num1.grabFocus();
    }//GEN-LAST:event_Btt_newActionPerformed

    private void Btt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_exitActionPerformed
       System.exit(0);
        
    }//GEN-LAST:event_Btt_exitActionPerformed

    private void Btt_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_sumaActionPerformed
        // TODO add your handling code here:
        this.Metodo_suma();
       
    }//GEN-LAST:event_Btt_sumaActionPerformed

    private void Txt_rtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_rtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_rtaActionPerformed

    private void Txt_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_num1ActionPerformed

    private void Btt_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_multiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btt_multiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_exit;
    private javax.swing.JButton Btt_multi;
    private javax.swing.JButton Btt_new;
    private javax.swing.JButton Btt_resta;
    private javax.swing.JButton Btt_suma;
    private javax.swing.JTextField Txt_num1;
    private javax.swing.JTextField Txt_num2;
    private javax.swing.JTextField Txt_rta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public void Metodo_suma()
{
int num1=Integer.parseInt(Txt_num1.getText());
int num2=Integer.parseInt(Txt_num2.getText());
oper.metodo_suma(num1, num2);
Txt_rta.setText(String.valueOf(oper.suma));
}

}
